"""Package the application into something you can send to someone.

    .venv\\Scripts\\python build.py           -> dist/Flashwatch.exe   (one file)
    .venv\\Scripts\\python build.py --dir     -> dist/Flashwatch/      (a folder)

One file is what you want for sending: the recipient downloads a single .exe and
double-clicks it. The cost is start-up time -- Windows has to unpack the bundle
into a temporary directory on every launch, which takes a few seconds -- so the
folder build stays available for anyone who runs it often.

Nothing here is specific to this machine: the same command works on any checkout
with the requirements installed.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENTRY = ROOT / "src" / "main.py"
ICON = ROOT / "build" / "flashwatch.ico"
NAME = "Flashwatch"

# Files PyInstaller collects that this application never opens. Excluding a
# *module* is not enough for these: they are DLLs and data pulled in by the
# PySide6 and OpenCV hooks, so they have to be filtered out of the bundle itself,
# which is what the generated spec below does.
#
# Every entry was measured in a dir build before being listed (see the README
# table). Together they are about two thirds of the raw bundle.
DROP_BINARIES = [
    # OpenCV's video pipeline. Nothing here decodes a video file: capture is
    # screenshots, and every cv2 call in src/ is arrays, morphology or drawing.
    "opencv_videoio_ffmpeg",
    # Mesa's software OpenGL, a fallback for Qt Quick and OpenGL widgets. This is
    # a QWidget application that paints with the raster engine.
    "opengl32sw.dll",
    "d3dcompiler_47.dll",
    "libegl.dll", "libglesv2.dll",
    # Qt libraries for the module families already excluded above. Their Python
    # bindings are gone, but the hook still ships the C++ libraries.
    "qt6quick", "qt6qml", "qt6pdf", "qt6network", "qt6svg", "qt6multimedia",
    "qt6charts", "qt6datavisualization", "qt63d", "qt6test", "qt6sql",
    "qt6websockets", "qt6webchannel", "qt6virtualkeyboard", "qt6opengl",
    "qt6spatialaudio", "qt6texttospeech", "qt6serialport", "qt6bluetooth",
    # Pillow codecs for formats that never appear here. Pillow itself stays:
    # rapidocr imports it. Its plugin registration tolerates a missing codec.
    "pil\\_avif", "pil/_avif", "pil\\_webp", "pil/_webp",
    "pil\\_jpeg2k", "pil/_jpeg2k",
]

# Qt plugins to leave out, matched on their folder. The platform plugin and the
# native style are what make the windows appear and look right; the rest are for
# databases, media, and image formats no icon here uses.
DROP_PLUGIN_DIRS = [
    "sqldrivers", "multimedia", "canbus", "designer", "qmltooling",
    "position", "renderers", "sensors", "texttospeech", "webview",
    "virtualkeyboard", "networkinformation", "tls",
]

# Data files: Qt's translations are ~40 .qm catalogues for an interface that
# ships its own strings, and qml/ belongs to a module family already dropped.
DROP_DATA = ["pyside6/translations", "pyside6\\translations",
             "pyside6/qml", "pyside6\\qml",
             "pyside6/resources", "pyside6\\resources"]

# Modules PyInstaller would otherwise pull in "just in case". PySide6 ships a
# large family of libraries and this application uses three of them; QtWebEngine
# alone is over 100 MB.
EXCLUDES = [
    "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick", "PySide6.QtQuick", "PySide6.QtQuick3D",
    "PySide6.QtQml", "PySide6.QtQmlModels", "PySide6.Qt3DCore",
    "PySide6.Qt3DRender", "PySide6.QtCharts", "PySide6.QtDataVisualization",
    "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets", "PySide6.QtPdf",
    "PySide6.QtPdfWidgets", "PySide6.QtOpenGL", "PySide6.QtOpenGLWidgets",
    "PySide6.QtSql", "PySide6.QtTest", "PySide6.QtDesigner",
    "PySide6.QtBluetooth", "PySide6.QtSerialPort", "PySide6.QtSpatialAudio",
    "PySide6.QtTextToSpeech", "PySide6.QtWebSockets", "PySide6.QtWebChannel",
    "tkinter", "matplotlib", "scipy", "pandas", "IPython", "pytest",
    "notebook", "sqlite3", "unittest",
]


SPEC_TEMPLATE = '''# Generated by build.py -- edit build.py, not this file.
import os

from PyInstaller.utils.hooks import collect_all, collect_dynamic_libs

DROP_BINARIES = {drop_binaries!r}
DROP_PLUGIN_DIRS = {drop_plugin_dirs!r}
DROP_DATA = {drop_data!r}

# The OCR models and the config naming them are package data, invisible to import
# analysis. Without this the app starts and then fails at the first chat read.
ocr_datas, ocr_binaries, ocr_hidden = collect_all("rapidocr_onnxruntime")
ocr_binaries += collect_dynamic_libs("onnxruntime")


def _drop(dest, patterns):
    dest = dest.replace("\\\\", "/").lower()
    name = os.path.basename(dest)
    for pattern in patterns:
        pattern = pattern.replace("\\\\", "/").lower()
        if pattern in dest or pattern in name:
            return True
    return False


def _keep_binary(dest):
    if _drop(dest, DROP_BINARIES):
        return False
    parts = dest.replace("\\\\", "/").lower().split("/")
    if "plugins" in parts:
        folder = parts[parts.index("plugins") + 1] if len(parts) > parts.index("plugins") + 1 else ""
        if folder in DROP_PLUGIN_DIRS:
            return False
    return True


analysis = Analysis(
    [{entry!r}],
    pathex=[{src!r}],
    binaries=ocr_binaries,
    datas=ocr_datas,
    hiddenimports=ocr_hidden + ["keyboard"],
    excludes={excludes!r},
    noarchive=False,
)

kept_binaries = [item for item in analysis.binaries if _keep_binary(item[0])]
kept_datas = [item for item in analysis.datas if not _drop(item[0], DROP_DATA)]
dropped = (len(analysis.binaries) - len(kept_binaries)
           + len(analysis.datas) - len(kept_datas))
print(f"build.py: left out {{dropped}} collected files")
analysis.binaries = kept_binaries
analysis.datas = kept_datas

pyz = PYZ(analysis.pure)
'''

SPEC_ONEFILE = '''
exe = EXE(
    pyz, analysis.scripts, analysis.binaries, analysis.datas,
    name={name!r}, console={console}, icon={icon!r}, upx=False,
    strip=False, bootloader_ignore_signals=False, disable_windowed_traceback=False,
)
'''

SPEC_ONEDIR = '''
exe = EXE(
    pyz, analysis.scripts, exclude_binaries=True,
    name={name!r}, console={console}, icon={icon!r}, upx=False, strip=False,
)
collected = COLLECT(exe, analysis.binaries, analysis.datas,
                    name={name!r}, upx=False, strip=False)
'''


def write_spec(one_file: bool, icon: Path | None,
               console: bool = False) -> Path:
    """Generate the spec. Kept generated rather than hand-maintained so the
    exclusion lists live next to the comments explaining them.

    ``console`` builds a version that keeps its terminal. Useless for playing --
    a console window over the game -- but it is the only way to see why a
    packaged build refuses to start, since a windowed one has nowhere to print
    the error to.
    """
    body = SPEC_TEMPLATE.format(
        drop_binaries=DROP_BINARIES, drop_plugin_dirs=DROP_PLUGIN_DIRS,
        drop_data=DROP_DATA, entry=str(ENTRY), src=str(ROOT / "src"),
        excludes=EXCLUDES,
    )
    tail = (SPEC_ONEFILE if one_file else SPEC_ONEDIR).format(
        name=NAME, icon=str(icon) if icon is not None else None,
        console=bool(console))
    path = ROOT / "build" / f"{NAME}.spec"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body + tail, "utf-8")
    return path


def make_icon() -> Path | None:
    """Draw the tray icon into an .ico, so the file has a face of its own.

    Same shape as the tray icon drawn at runtime in main.py: an unbranded dark
    disc with a clock hand. Deliberately nothing resembling Riot's artwork.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("Pillow missing, building without a custom icon")
        return None

    size = 256
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.ellipse([8, 8, size - 8, size - 8], fill=(22, 26, 36, 255),
                 outline=(90, 200, 255, 255), width=10)
    centre = size // 2
    draw.line([centre, centre, centre, 60], fill=(240, 248, 255, 255), width=14)
    draw.line([centre, centre, centre + 58, centre + 30],
              fill=(240, 248, 255, 255), width=14)
    draw.ellipse([centre - 10, centre - 10, centre + 10, centre + 10],
                 fill=(90, 200, 255, 255))

    ICON.parent.mkdir(parents=True, exist_ok=True)
    image.save(ICON, sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64),
                            (128, 128), (256, 256)])
    return ICON


def target_is_locked(target: Path) -> bool:
    """Whether ``target`` is held open, typically by a copy that is running.

    Checked up front rather than letting PyInstaller fail: it spends a minute
    collecting everything before touching the output, and "Accès refusé" after
    that minute says nothing about what to do.
    """
    if not target.exists():
        return False
    try:
        # Opening for update is the probe that works on Windows: a running image
        # cannot be opened for writing. Renaming it can -- Windows allows an
        # executing file to be renamed, which is why that test looked fine and
        # let the build fail a minute later.
        with open(target, "r+b"):
            return False
    except OSError:
        return True


def main() -> int:
    one_file = "--dir" not in sys.argv

    if not ENTRY.exists():
        print(f"cannot find {ENTRY}")
        return 1

    # --out builds somewhere else, which is how to produce a new binary while a
    # copy is still running: Windows will not let anything overwrite a running
    # image, and the only alternative is closing the program first.
    dist = ROOT / "dist"
    if "--out" in sys.argv:
        index = sys.argv.index("--out")
        if index + 1 >= len(sys.argv):
            print("--out needs a directory")
            return 1
        dist = Path(sys.argv[index + 1]).resolve()

    output = dist / (f"{NAME}.exe" if one_file else NAME)
    if one_file and target_is_locked(output):
        print(f"{output} is in use -- close the running {NAME} first "
              f"(tray icon -> Quitter), or build elsewhere with "
              f"--out <directory>.")
        return 1
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller is missing. Install it with:\n"
              "    .venv\\Scripts\\python -m pip install pyinstaller")
        return 1

    icon = make_icon()
    spec = write_spec(one_file, icon, console="--console" in sys.argv)
    # A spec rather than command-line flags: the biggest savings are DLLs and data
    # the hooks collect on their own, and only a spec can filter those. The window
    # style, icon and hidden imports live in the generated file too.
    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--distpath", str(dist),
        "--workpath", str(ROOT / "build"),
        str(spec),
    ]

    print(" ".join(command), "\n")
    result = subprocess.run(command, cwd=ROOT)
    if result.returncode != 0:
        return result.returncode

    target = output
    if not target.exists():
        print(f"build reported success but {target} is missing")
        return 1

    if one_file:
        size = target.stat().st_size / (1024 * 1024)
        print(f"\nBuilt {target}  ({size:.0f} MB)")
        print("Send that single file. First launch downloads champion icons, so "
              "it needs a working internet connection once.")
    else:
        total = sum(f.stat().st_size for f in target.rglob("*") if f.is_file())
        print(f"\nBuilt {target}\\{NAME}.exe  "
              f"({total / (1024 * 1024):.0f} MB in the folder)")
        print("Zip the whole folder to send it; the .exe alone will not run.")
    return 0


def clean() -> None:
    for directory in (ROOT / "build", ROOT / "dist"):
        shutil.rmtree(directory, ignore_errors=True)


if __name__ == "__main__":
    if "--clean-only" in sys.argv:
        clean()
        print("removed build/ and dist/")
        sys.exit(0)
    sys.exit(main())
